// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailTrade.EntityFramework;

#nullable disable

namespace RetailTrade.EntityFramework.Migrations
{
    [DbContext(typeof(RetailTradeDbContext))]
    [Migration("20220527050407_ProductsWareHousesDefaultValues")]
    partial class ProductsWareHousesDefaultValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RetailTrade.Domain.Models.Arrival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("WareHouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WareHouseId");

                    b.ToTable("Arrivals");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ArrivalProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArrivalId")
                        .HasColumnType("int");

                    b.Property<decimal>("ArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ArrivalSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("ProductId");

                    b.ToTable("ArrivalProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OKPO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractorTypeId");

                    b.ToTable("Contractors");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Contractor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractorTypeId = 2,
                            Created = new DateTime(1995, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Розничный покупатель",
                            IsDeleted = false,
                            WorkName = "Розничный покупатель"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ContractorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContractorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Юридическое лицо"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Физическое лицо"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int>("GroupEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("GroupEmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мужской"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Женский"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.GroupEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubGroupId");

                    b.ToTable("GroupsEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Сотрудники"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Руководство",
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кассиры",
                            SubGroupId = 1
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.LabelPriceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("LabelPriceTagSizeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeLabelPriceTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabelPriceTagSizeId");

                    b.HasIndex("TypeLabelPriceTagId");

                    b.ToTable("LabelPriceTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LabelPriceTagSizeId = 1,
                            Name = "Этикетка для товара",
                            TypeLabelPriceTagId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ценник для товара",
                            TypeLabelPriceTagId = 2
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.LabelPriceTagSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("TypeLabelPriceTagId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeLabelPriceTagId");

                    b.ToTable("LabelPriceTagSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 250,
                            TypeLabelPriceTagId = 1,
                            Width = 460
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderToSupplierId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderToSupplierId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ожидается поступление"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Закрыт"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Не выполнено"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderToSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OrdersToSuppliers");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteMark")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("TNVED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeProductId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<bool>("WithoutBarcode")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TypeProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ProductRefund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("RefundId")
                        .HasColumnType("int");

                    b.Property<int>("RefundtId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RefundId");

                    b.ToTable("ProductRefunds");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ProductSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ProductSales");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ProductWareHouse", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WareHouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("ArrivalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<double>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("ProductId", "WareHouseId");

                    b.HasIndex("WareHouseId");

                    b.ToTable("ProductsWareHouses", (string)null);
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AmountWithoutDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<string>("KKMCheckNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidInCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidInCashless")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfRefund")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RefundToSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefundToSupplierDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("RefundsToSuppliers");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RefundToSupplierProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RefundToSupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RefundToSupplierId");

                    b.ToTable("RefundToSupplierProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Revaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevaluationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Revaluations");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RevaluationProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldArrivalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RevaluationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RevaluationId");

                    b.ToTable("RevaluationProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кассир"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeLabelPriceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeLabelPriceTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Этикетка для товаров"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ценник для товаров"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubGroupId");

                    b.ToTable("TypeProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsGroup = true,
                            Name = "Виды товаров"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeWareHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeWareHouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Склад"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Розничный магазин"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LongName = "Килограмм",
                            ShortName = "кг"
                        },
                        new
                        {
                            Id = 2,
                            LongName = "Грамм",
                            ShortName = "г"
                        },
                        new
                        {
                            Id = 3,
                            LongName = "Литр",
                            ShortName = "л"
                        },
                        new
                        {
                            Id = 4,
                            LongName = "Метр",
                            ShortName = "м"
                        },
                        new
                        {
                            Id = 5,
                            LongName = "Штука",
                            ShortName = "шт"
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("DeleteMark")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WareHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteMark")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeWareHouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeWareHouseId");

                    b.ToTable("WareHouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeleteMark = false,
                            Name = "Розничный магазин",
                            TypeWareHouseId = 0
                        },
                        new
                        {
                            Id = 2,
                            DeleteMark = false,
                            Name = "Основной склад",
                            TypeWareHouseId = 0
                        });
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WriteDown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WriteDownDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("WriteDowns");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WriteDownProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("WriteDownId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WriteDownId");

                    b.ToTable("WriteDownProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Customer", b =>
                {
                    b.HasBaseType("RetailTrade.Domain.Models.Contractor");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("GenderId");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Arrival", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.WareHouse", "WareHouse")
                        .WithMany("Arrivals")
                        .HasForeignKey("WareHouseId");

                    b.Navigation("Supplier");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ArrivalProduct", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Arrival", "Arrival")
                        .WithMany("ArrivalProducts")
                        .HasForeignKey("ArrivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("ArrivalProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arrival");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Branch", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.User", "User")
                        .WithOne("Branch")
                        .HasForeignKey("RetailTrade.Domain.Models.Branch", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Contractor", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.ContractorType", "ContractorType")
                        .WithMany("Contractors")
                        .HasForeignKey("ContractorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractorType");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Employee", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.GroupEmployee", "GroupEmployee")
                        .WithMany("Employees")
                        .HasForeignKey("GroupEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("GroupEmployee");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.GroupEmployee", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.GroupEmployee", "SubGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.LabelPriceTag", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.LabelPriceTagSize", "LabelPriceTagSize")
                        .WithMany("LabelPriceTags")
                        .HasForeignKey("LabelPriceTagSizeId");

                    b.HasOne("RetailTrade.Domain.Models.TypeLabelPriceTag", "TypeLabelPriceTag")
                        .WithMany("LabelPriceTags")
                        .HasForeignKey("TypeLabelPriceTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabelPriceTagSize");

                    b.Navigation("TypeLabelPriceTag");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.LabelPriceTagSize", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.TypeLabelPriceTag", "TypeLabelPriceTag")
                        .WithMany("LabelPriceTagSizes")
                        .HasForeignKey("TypeLabelPriceTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeLabelPriceTag");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderProduct", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.OrderToSupplier", "OrderToSupplier")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderToSupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderToSupplier");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderToSupplier", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Product", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");

                    b.HasOne("RetailTrade.Domain.Models.TypeProduct", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("TypeProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("TypeProduct");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ProductRefund", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("ProductRefunds")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Refund", "Refund")
                        .WithMany("ProductRefunds")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ProductSale", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("ProductSales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Receipt", "Receipt")
                        .WithMany("ProductSales")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ProductWareHouse", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("ProductsWareHouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.WareHouse", "WareHouse")
                        .WithMany("ProductsWareHouses")
                        .HasForeignKey("WareHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Receipt", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Shift", "Shift")
                        .WithMany("Receipts")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Refund", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Shift", "Shift")
                        .WithMany("Refunds")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RefundToSupplier", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RefundToSupplierProduct", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("ProductRefundToSuppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.RefundToSupplier", "RefundToSupplier")
                        .WithMany("RefundToSupplierProducts")
                        .HasForeignKey("RefundToSupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RefundToSupplier");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RevaluationProduct", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("RevaluationProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.Revaluation", "Revaluation")
                        .WithMany("RevaluationProducts")
                        .HasForeignKey("RevaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Revaluation");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Shift", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeProduct", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.TypeProduct", "SubGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.User", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WareHouse", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.TypeWareHouse", "TypeWareHouse")
                        .WithMany("WareHouses")
                        .HasForeignKey("TypeWareHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeWareHouse");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WriteDown", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WriteDownProduct", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Product", "Product")
                        .WithMany("WriteDownProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailTrade.Domain.Models.WriteDown", "WriteDown")
                        .WithMany("WriteDownProducts")
                        .HasForeignKey("WriteDownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WriteDown");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Customer", b =>
                {
                    b.HasOne("RetailTrade.Domain.Models.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Arrival", b =>
                {
                    b.Navigation("ArrivalProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.ContractorType", b =>
                {
                    b.Navigation("Contractors");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Gender", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.GroupEmployee", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.LabelPriceTagSize", b =>
                {
                    b.Navigation("LabelPriceTags");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.OrderToSupplier", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Product", b =>
                {
                    b.Navigation("ArrivalProducts");

                    b.Navigation("Orders");

                    b.Navigation("ProductRefundToSuppliers");

                    b.Navigation("ProductRefunds");

                    b.Navigation("ProductSales");

                    b.Navigation("ProductsWareHouses");

                    b.Navigation("RevaluationProducts");

                    b.Navigation("WriteDownProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Receipt", b =>
                {
                    b.Navigation("ProductSales");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Refund", b =>
                {
                    b.Navigation("ProductRefunds");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.RefundToSupplier", b =>
                {
                    b.Navigation("RefundToSupplierProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Revaluation", b =>
                {
                    b.Navigation("RevaluationProducts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Shift", b =>
                {
                    b.Navigation("Receipts");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Supplier", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeLabelPriceTag", b =>
                {
                    b.Navigation("LabelPriceTagSizes");

                    b.Navigation("LabelPriceTags");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeProduct", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.TypeWareHouse", b =>
                {
                    b.Navigation("WareHouses");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.User", b =>
                {
                    b.Navigation("Branch");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WareHouse", b =>
                {
                    b.Navigation("Arrivals");

                    b.Navigation("ProductsWareHouses");
                });

            modelBuilder.Entity("RetailTrade.Domain.Models.WriteDown", b =>
                {
                    b.Navigation("WriteDownProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
