//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailTradeClient.Report {
    
    public partial class XReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "RetailTradeClient.Report.XReport.vsrepx");

            // Controls
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.detailBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("detailBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.Address = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Address");
            this.OrganizationName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("OrganizationName");
            this.SubBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand1");
            this.line2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.lbReportDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbReportDate");
            this.lbShiftNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbShiftNumber");
            this.lbStartShift = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbStartShift");
            this.line3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line3");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.lbCashSum = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbCashSum");
            this.lbCashlessSum = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbCashlessSum");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.lbReceiptCount = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbReceiptCount");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.lbCashOnHand = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbCashOnHand");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.line4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line4");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.lbShiftTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbShiftTotal");
            this.lbCashierName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbCashierName");
        }
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.DetailBand detailBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.XRLabel Address;
        private DevExpress.XtraReports.UI.XRLabel OrganizationName;
        private DevExpress.XtraReports.UI.SubBand SubBand1;
        private DevExpress.XtraReports.UI.XRLine line2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRLabel lbReportDate;
        private DevExpress.XtraReports.UI.XRLabel lbShiftNumber;
        private DevExpress.XtraReports.UI.XRLabel lbStartShift;
        private DevExpress.XtraReports.UI.XRLine line3;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel lbCashSum;
        private DevExpress.XtraReports.UI.XRLabel lbCashlessSum;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRLabel lbReceiptCount;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.XRLabel lbCashOnHand;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRLine line4;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.XRLabel lbShiftTotal;
        private DevExpress.XtraReports.UI.XRLabel lbCashierName;
    }
}
