//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailTrade.Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int Id { get; set; }
        public decimal Quantity { get; set; }
        public decimal Sum { get; set; }
        public int ProductId { get; set; }
        public int ReceiptId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Receipts Receipts { get; set; }
    }
}
