//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailTrade.Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductSales = new HashSet<ProductSales>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProductSubcategoryId { get; set; }
        public int SupplierId { get; set; }
        public int UnitId { get; set; }
        public int TNVED { get; set; }
        public string Barcode { get; set; }
        public decimal ArrivalPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal SalePrice { get; set; }
        public bool WithoutBarcode { get; set; }
    
        public virtual ProductSubcategories ProductSubcategories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSales> ProductSales { get; set; }
    }
}
