//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailTrade.Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int Id { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public int ShiftId { get; set; }
        public decimal Sum { get; set; }
        public decimal Change { get; set; }
        public decimal PaidInCash { get; set; }
        public decimal PaidInCashless { get; set; }
    }
}
