using DevExpress.DashboardCommon;
using DevExpress.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;

namespace RetailTrade.Dashboard
{
    public partial class TestDashboard : DevExpress.DashboardCommon.Dashboard
    {
        public TestDashboard()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            RetailTrade.Dashboard.RetailTradeDbEntities dbContext = new RetailTrade.Dashboard.RetailTradeDbEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Receipts.Load();
            // This line of code is generated by Data Source Configuration Wizard
            Receipts.DataSource = dbContext.Receipts.Local.ToBindingList();
        }
    }
}
